import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/context/AuthContex";
import '@radix-ui/themes/styles.css';
import "./globals.css";
import { Theme } from "@radix-ui/themes";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "VisDebugger",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark">
          <AuthContextProvider>
          {children}
          </AuthContextProvider>
        </Theme>
        </body>

    </html>
   
  );
}
